### ISSUE TITLE
No Generation / Inpainting

### ISSUE THREAD

**Issue by alexanderdutton** [ahrm/UnstableFusion#1]
This is a very cool project, thank you for sharing!

Both locally and from the colab, I am given an error popup when trying to generate or inpaint. I am able to free-paint on the canvas with the cursor.

I'm running on Windows 10, ensured to have every dependency, and ran Conda Powershell as an admin.

An error I received when running the server:

> DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
>   strength_slider.setValue(value)

I also have an issue with the Tool interface being too tall for my screen, but that's likely because I'm using an unusual resolution -- I doubt it is the cause, but thought it worth mentioning.

Thanks!

**Comment by ahrm** [comment]
This is just a warning and not an important problem. Sometimes when the selection box is out of bound there is an error. Make sure to select a small box and see if the issue persists.

Also I have updated the repo in 98959fbe91494773267f4090b2c7b73f1383f0be to log more descriptive error messages. Use this version if the issue persists and you should see a more descriptive error message.
