### ISSUE TITLE
ValueError: could not broadcast input array from shape

### ISSUE THREAD

**Issue by ZeroCool22** [ahrm/UnstableFusion#11]
When use the function **paste from scratchpad**.

![Screenshot_36](https://user-images.githubusercontent.com/13344308/192037813-f66eb200-adc9-4146-b252-c5b5c43ff997.jpg)

**Comment by ahrm** [comment]
I think this only happens when the source box in the scratchpad is out of bounds, am I correct?

**Comment by ZeroCool22** [comment]
> out of bounds

Could be....

**Comment by ahrm** [comment]
Should be fixed in 98b53112bb334b8deaf39d98fdfcd8670787a260.
