### ISSUE TITLE
How increase the size of the Red Rectangle without affecting the object?

### ISSUE THREAD

**Issue by ZeroCool22** [ahrm/UnstableFusion#12]
In your video:

![capture2](https://user-images.githubusercontent.com/13344308/192039582-93523f7e-3573-4deb-9b31-c7cf1e9024a8.gif)

When i increase the **Red Rectangle**, it also increases the subject/object:

![sdsdssaaaaaa](https://user-images.githubusercontent.com/13344308/192039674-f557a897-be09-4ffb-81d2-890cd9d3c096.gif)

**Comment by ahrm** [comment]
In the video I first paste the image (by pressing `p`) then I hide the scratchpad preview (by pressing `t`) and then I scale the image.
