### ISSUE TITLE
Reimagine stopped working

### ISSUE THREAD

**Issue by Airburner** [ahrm/UnstableFusion#17]
Hey there, 

Unfortunately reimagine element stopped working 
  File "D:\AI\UnstableFusion-main\unstablefusion.py", line 767, in handle_reimagine_button
    reimagined_image = self.get_handler().reimagine(prompt,
TypeError: ServerStableDiffusionHandler.reimagine() got an unexpected keyword argument 'strength'

(using newest collab link + package from github)

**Comment by ahrm** [comment]
Should be fixed now.
