### ISSUE TITLE
KeyError: 'image_size'

### ISSUE THREAD

**Issue by Motshew** [ahrm/UnstableFusion#19]
I'm receiving an error when I try to generate, reimagine, or inpaint. This with the webui up and it is being pointed to the server address.
when i click any of those options, I receive this error in the console,

size = resp_data['image_size']
KeyError: 'image_size'

**Comment by ahrm** [comment]
Are you using the latest version of the repository?
And by webui you mean google colab, right?

**Comment by Motshew** [comment]
im running stable diffusion locally. and yeah, just cloned it an hour ago

**Comment by ahrm** [comment]
By locally you mean Automatic1111's webui? If so, we don't support that yet.

**Comment by Motshew** [comment]
ah, well that would do it then. thanks for clearing that up!
