### ISSUE TITLE
Make the canvas scrollable.

### ISSUE THREAD

**Issue by ZeroCool940711** [ahrm/UnstableFusion#32]
Hi there, I found this repo recently and after testing it a bit I fell in love with the way it works and the results you can get with it, Ive test other similar inpainting implementations but this one is pretty solid. One thing I did notice is the lack of scroll on the canvas or the area where the image is drawn/generated, with this tool it is possible to slowly create a huge image made in chunks with anything we want on it, not being able to scroll to the sides or up and down reduces the workable area we have and makes it so the size of what we can create is limited, if we had some scroll bars on the side or bottom part of the canvas so we can move it would be awesome and the possibilities with it are endless, even better would be to have a shortcut or something like middle mouse button for scrolling in the mouse direction, an extra thing that would be nice to have would be zooming in an out. I really hope some of these features could be added as it would improve things a lot. Thanks for your time, and thanks for making this :)

**Comment by ahrm** [comment]
>  an extra thing that would be nice to have would be zooming in an out.

You can already do this by pressing control and using mouse wheel.

**Comment by ahrm** [comment]
Added scrolling in 81ff6f1bfaea96fe5f2a09869a18b33d9ce0f634. You can also use shift+mouse wheel to scroll horizontally and control+shift+mouse wheel to scroll vertically.

**Comment by ZeroCool940711** [comment]
@ahrm thanks man, really appreciate it, keep the good work.
