### ISSUE TITLE
This line from the readme needs to explicitly install pytorch with cuda enabled

### ISSUE THREAD

**Issue by calebrader** [ahrm/UnstableFusion#41]
pip install -r requirements-localgpu-win64.txt

**Comment by calebrader** [comment]
The problem is that even when following all the directions in the readme, this error still occurs:

```
File "C:\Python310\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by ahrm** [comment]
You need to first install a compatible version of cuda (for example pytorch 1.13 is only compatible with cuda 11.6 and 11.7) and then install gpu version of pytorch. The exact command to install torch can be found in the pytorch website. Something like this:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
```
