### ISSUE TITLE
Readme and requirements leave out qasync and httpx

### ISSUE THREAD

**Issue by calebrader** [ahrm/UnstableFusion#42]

**Comment by ahrm** [comment]
The readme does, but it is in the requirements:

[qasync>=0.23.0](https://github.com/ahrm/UnstableFusion/blob/b25169054c1b10960f7d5bcee3ad31828d44e5cc/requirements-localgpu-win64.txt#L13)

**Comment by eahenle** [comment]
made a PR: #44
