### ISSUE TITLE
Executing the instructions in google collab returns an error

### ISSUE THREAD

**Issue by Vponed** [ahrm/UnstableFusion#43]
Fetching 15 files: 100%
15/15 [00:00<00:00, 545.25it/s]

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-21-023fa79c03c6>](https://localhost:8080/#) in <module>
----> 1 run_app()

2 frames

[/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    514                         class_obj()
    515 
--> 516                     raise ValueError(
    517                         f"The component {class_obj} of {pipeline_class} cannot be loaded as it does not seem to have"
    518                         f" any of the loading methods defined in {ALL_IMPORTABLE_CLASSES}."

ValueError: The component <class 'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> cannot be loaded as it does not seem to have any of the loading methods defined in {'ModelMixin': ['save_pretrained', 'from_pretrained'], 'SchedulerMixin': ['save_config', 'from_config'], 'DiffusionPipeline': ['save_pretrained', 'from_pretrained'], 'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizer': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained', 'from_pretrained'], 'PreTrainedModel': ['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin': ['save_pretrained', 'from_pretrained']}.

**Comment by ahrm** [comment]
Should be fixed in the latest commit.
