### ISSUE TITLE
Turn off Safety Check.

### ISSUE THREAD

**Issue by ZeroCool22** [ahrm/UnstableFusion#5]
What i need to change here?

```
def dummy_safety_checker(self):
        def check(images, *args, **kwargs):
            return images, [False] * len(images)
```
For this?:

```
def dummy_safety_checker(self):
        def check(images, *args, **kwargs):
            return images, [True] * len(images)
```

Or there is something more i need to modify?

**PD:** I run it Locally, no on Collab.

**Comment by ahrm** [comment]
Added a button to disable safety checker in the latest commits.
Note that it only works in the local colab, and you should press it after you have already generated am image (so that we have created a pipeline that we can disable safety on).

**Comment by ZeroCool22** [comment]
> Added a button to disable safety checker in the latest commits. Note that it only works in the local colab, and you should press it after you have already generated am image (so that we have created a pipeline that we can disable safety on).

Great, thx!

**Comment by Muhammad-Zubair** [comment]
uncommented the code line but still got nsfw content error message, there is no visible button on gui to turn of the filter

**Comment by ahrm** [comment]
What code line?

**Comment by Muhammad-Zubair** [comment]
# self.text2img.safety_checker = dummy_safety_checker 
in diffusionserver.py file to disable filter running front end on my local pc + colab

**Comment by ahrm** [comment]
That doesn't work. You need to use the newest commits and use the UI button to disable safety checker (see the post above).

**Comment by Muhammad-Zubair** [comment]
can you make it easy to turn off the filter just add a button in gui to enable or disable before generating an image or inpainting for all functions it will be more suitable that way. thanks

**Comment by ahrm** [comment]
I intent to do that.

**Comment by Muhammad-Zubair** [comment]
when it will be available? actually I'm very bad at oop else I was gonna do it myself

**Comment by ahrm** [comment]
I am not sure, I am focused on fixing compatibility issues right now rather than adding new features. I would say I will probably implement it by tomorrow.

**Comment by ZeroCool22** [comment]
![Screenshot_30](https://user-images.githubusercontent.com/13344308/191995471-0ebf8d0a-00bc-4098-b106-f2bdb5b2e001.jpg)

**Comment by ahrm** [comment]
Disabled safety checker by default in the newest commit. Now should work with colab too.

**Comment by Muhammad-Zubair** [comment]
ok that will be cool

**Comment by Muhammad-Zubair** [comment]
another thing that I want to mention gui box is of fix height due to that unable to see the buttons beneath export button, for that I have to maximize it, so enable the dynamic (adjustable) height.

**Comment by ahrm** [comment]
> another thing that I want to mention gui box is of fix height due to that unable to see the buttons beneath export button, for that I have to maximize it, so enable the dynamic (adjustable) height.

Should be fixed in the latest commits.
