### ISSUE TITLE
Any plans to tag a release? asking for Flathub

### ISSUE THREAD

**Issue by nbenitez** [ahrm/UnstableFusion#51]
Hi, I'm the packager of Sioyek for Flathub and noticed this other super cool project of yours. It would be nice to have it in Flathub too, but Flathub has a policy to only build from a tag (so not from a commit or branch tip). So two questions:

Are you ok with publishing UnstableFusion in www.flathub.org ?
Are you planning to tag a release for UnstableFusion ?

Thanks :-) ,

**Comment by ahrm** [comment]
> Are you ok with publishing UnstableFusion in [www.flathub.org](http://www.flathub.org/) ?

Yes.

> Are you planning to tag a release for UnstableFusion ?

Done.

And thanks for your work on sioyek package.

**Comment by nbenitez** [comment]
You're welcome, thanks for Sioyek and keep up your good work! :-)
