### ISSUE TITLE
'NoneType' object has no attribute 'width'

### ISSUE THREAD

**Issue by ZeroCool22** [ahrm/UnstableFusion#6]
```
C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>python unstablefusion.py
'NoneType' object has no attribute 'width'
'NoneType' object has no attribute 'width'
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion\unstablefusion.py", line 565, in mousePressEvent
    top_left = QPoint(e.pos().x() - self.selection_rectangle_size[0] / 2, e.pos().y() - self.selection_rectangle_size[1] / 2)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'

C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>
```

https://user-images.githubusercontent.com/13344308/191976776-ab6a9235-a799-4ea8-9158-d7e3a55325f5.mp4

And just doing a **Click on the Canvas**, gives an error too and close it by itself.

https://user-images.githubusercontent.com/13344308/191977180-b545d36c-af42-446a-a1c8-6a948e1c173f.mp4

**Comment by ahrm** [comment]
You must select a target square before trying to generate.

**Comment by ZeroCool22** [comment]
> You must select a target square before trying to generate.

Look the **second video** when i try to click the canvas i get error too...

**Comment by ahrm** [comment]
Are you sure you are using the latest commits? This line of code should be different in the latest commits.

**Comment by ZeroCool22** [comment]
> Are you sure you are using the latest commits? This line of code should be different in the latest commits.

Let me do a GIT PULL and i will try again..

**Comment by ZeroCool22** [comment]
Ok:

```
C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>python unstablefusion.py
'NoneType' object has no attribute 'width'
You specified use_auth_token=True, but a Hugging Face token was not found.
```

I need a Token to Run it locally?

**Comment by ahrm** [comment]
Yes, you need to run a stable diffusion notebook locally once (so that your token is cached) for example this: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_diffusion.ipynb (download it and run it locally using jupyter notebook). After that you will be able to use unstablefusion.

**Comment by ZeroCool22** [comment]
> Yes, you need to run a stable diffusion notebook locally once (so that your token is cached) for example this: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_diffusion.ipynb (download it and run it locally using jupyter notebook). After that you will be able to use unstablefusion.

Never run a Jupiter Notebook before.
I just download it and now it opened in Studio Code:

![Screenshot_24](https://user-images.githubusercontent.com/13344308/191981170-414b1887-f76c-47c1-95b9-e669370b67d3.jpg)

Now i run every cell?

**Comment by ZeroCool22** [comment]
Ok, and now?:

![Screenshot_25](https://user-images.githubusercontent.com/13344308/191982701-6fe1eab2-be88-489f-be3e-50c5bd014637.jpg)

**Comment by ahrm** [comment]
Click on the note book and run the cells one-by-one. You probably won't need to run some of them like these:
```
!pip install diffusers==0.3.0
!pip install transformers scipy ftfy
!pip install "ipywidgets>=7,<8"
```
which are just installing the packages that you already have.

Also you don't need to run the colab-specific ones like this:
```
from google.colab import output
output.enable_custom_widget_manager()
```

The main cell that you have to run is this:
```
from huggingface_hub import notebook_login

notebook_login()
```

**Comment by ZeroCool22** [comment]
> Click on the note book and run the cells one-by-one. You probably won't need to run some of them like these:
> 
> ```
> !pip install diffusers==0.3.0
> !pip install transformers scipy ftfy
> !pip install "ipywidgets>=7,<8"
> ```
> 
> which are just installing the packages that you already have.
> 
> Also you don't need to run the colab-specific ones like this:
> 
> ```
> from google.colab import output
> output.enable_custom_widget_manager()
> ```
> 
> The main cell that you have to run is this:
> 
> ```
> from huggingface_hub import notebook_login
> 
> notebook_login()
> ```

![Screenshot_26](https://user-images.githubusercontent.com/13344308/191983809-35992fa2-886c-42ef-8e8e-fcb46d6ff1ca.jpg)

Still getting the **You specified use_auth_token=True, but a Hugging Face token was not found.**

**Comment by ahrm** [comment]
It may be a good idea to continue running the notebook until a stable diffusion pipeline is created.

**Comment by ZeroCool22** [comment]
Well, after downloading a lot of things this comes out..

![Screenshot_27](https://user-images.githubusercontent.com/13344308/191986856-e3c20382-0d47-428a-9be3-d3165fdedea6.jpg)

**Comment by ZeroCool22** [comment]
> Or you can edit the files and replace
> 
> ```
> use_auth_token=True
> ```
> 
> with
> 
> ```
> use_auth_token='<your huggingface token>'
> ```

In what file i modify that?

**Comment by ZeroCool22** [comment]
This one?

![Screenshot_28](https://user-images.githubusercontent.com/13344308/191988130-275b8911-be68-4aa7-bb94-b55770163c63.jpg)

use_auth_token=True).to("cuda")

For this?:

use_auth_token='xxxxxxxxxxxx').to("cuda")

**Comment by ahrm** [comment]
Added in aa5ffd5d34766df4197ecc376e701ed3cd688657.

**Comment by ZeroCool22** [comment]
C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>python unstablefusion.py
{'trained_betas'} was not found in config. Values will be initialized to default values.
Torch not compiled with CUDA enabled

**Comment by ahrm** [comment]
Well, you need pytorch with cuda enabled for stablediffusion. See the pytorch website for how to install pytorch with cuda enabled.

**Comment by ZeroCool22** [comment]
> Yes, however, I have made a version that has a field in the UI for huggingface token. I will upload it in a few minutes. You may want to wait for that.

Yeah!

Was about to tell if there wasn't a more easy way to handle the Token in the interface...

But what about the Torch error? :(

**Comment by ahrm** [comment]
Well, you need pytorch with cuda enabled for stablediffusion. See the pytorch website for how to install pytorch with cuda enabled.

**Comment by ZeroCool22** [comment]
> install pytorch with cuda

This could be included in the **requirements.txt**?

**Comment by ahrm** [comment]
The thing is, you don't need this if you intend to run it with google colab.

**Comment by ZeroCool22** [comment]
> The thing is, you don't need this if you intend to run it with google colab.

Yeah, but i always prefer run it locally! So use my own GPU....

**Comment by ZeroCool22** [comment]
![Screenshot_29](https://user-images.githubusercontent.com/13344308/191991254-e9a6dea0-511c-42a0-b751-6b114b8a8fe6.jpg)

What i should put here?

**Comment by ahrm** [comment]
You could just clone the repository from scratch (this is conflicting with the changes you have done, for example your hugginface token, in the new version we have a UI field for that so there is no need for your change anymore)

**Comment by ZeroCool22** [comment]
Can you help me with the Pytorch with CUDA install please?

https://pytorch.org/get-started/locally/

This will works?:

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`

**Comment by ZeroCool22** [comment]
> Yes.

![Screenshot_31](https://user-images.githubusercontent.com/13344308/191998745-7a3db153-42a7-46db-b87a-a75b790b84d6.jpg)

Well, i don't know what more to do...

**Comment by ahrm** [comment]
Did you install cuda itself?

**Comment by ZeroCool22** [comment]
> Did you install cuda itself?

![Screenshot_32](https://user-images.githubusercontent.com/13344308/192000093-8ae384db-6414-451c-8fe5-9b8d77544e22.jpg)


I used this command 

pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 

inside: 

C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion

**Comment by ZeroCool22** [comment]
Mmmm, or the command should have been run in C:\Windows\system32>?

**Comment by ahrm** [comment]
Your cuda version is too recent! You installed pytorch with cuda 11.3 but you have cuda 11.7. (I think pytorch only supports up to cuda 11.6)

**Comment by ZeroCool22** [comment]
> Your cuda version is too recent! You installed pytorch with cuda 11.3 but you have cuda 11.7. (I think pytorch only supports up to cuda 11.6)

How uninstall it?

Just from control panel? or must be from the console?

**Comment by ahrm** [comment]
I don't think you need to uninstall anything. Just install the other version. (not sure though)

**Comment by ZeroCool22** [comment]
> I don't think you need to uninstall anything. Just install the other version. (not sure though)

![Screenshot_33](https://user-images.githubusercontent.com/13344308/192012597-9e00c0d2-bb64-4873-abb4-f1ef1fad508b.jpg)

I tried with 3 different version, but when i run the command **nvidia-smi** still saying 1**1.7**.

I used the command

: pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

But it still says 11.7.

**Comment by ahrm** [comment]
You probably need to add the correct cuda version's bin directory to `PATH` and remove the old one from the `PATH`.

**Comment by ZeroCool22** [comment]
> You probably need to add the correct cuda version's bin directory to `PATH` and remove the old one from the `PATH`.

I installed the 11.3.

My PATHS are fine:

![capture](https://user-images.githubusercontent.com/13344308/192024528-181e9cc3-437e-4a5b-bb6c-2451b6bdda41.gif)

![Screenshot_34](https://user-images.githubusercontent.com/13344308/192024543-623255c7-636d-4673-b73e-7e05ce02fc44.jpg)

But i still get: Torch not compiled with CUDA enabled

What i do, i should try to install **Tensoroflow**?

**Comment by ahrm** [comment]
I am not sure. I would say at this point your issue is a pytorch issue rather than unstablediffusion issue. You may find better help in pytorch forums, I am not really an expert on this.

**Comment by ZeroCool22** [comment]
Finally, working...

![Screenshot_35](https://user-images.githubusercontent.com/13344308/192032519-bac1553a-2eea-45da-8297-13feefde6e82.jpg)


This can be ignored?:

{'trained_betas'} was not found in config. Values will be initialized to default values.

**Comment by ahrm** [comment]
Yes, that is not a problem.
