### ISSUE TITLE
Installed requirements, but getting this...

### ISSUE THREAD

**Issue by quinxy** [ahrm/UnstableFusion#8]
$ python unstablefusion.py 
QObject::moveToThread: Current thread (0x560370c73760) is not the object's thread (0x560374ec5b20).
Cannot move to target thread (0x560370c73760)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/user/anaconda3/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)

**Comment by ahrm** [comment]
I am not sure. Does this help: https://github.com/NVlabs/instant-ngp/discussions/300 ?

**Comment by quinxy** [comment]
Huh.  So this is weird.  Definitely didn't resolve the problem.

I don't get the crash, but it just hangs when I try to start it.  Now it just shows this and nothing else happens, ever.

> This plugin does not support propagateSizeHints()

I tried every other available platform plugin, and very, very strangely (to me anyway), the only one that didn't crash or hang was VNC.  And, the VNC one actually worked!?!?  It runs a vnc server and so i have to use a VNC client to see your interface.  Not a great solution, but it does, technically, work.

**Comment by manugarri** [comment]
same here.

**Comment by ahrm** [comment]
A user in reddit suggested this:
```
pip uninstall opencv-python     (solve a xcb compatibility issue)

pip install opencv-python-headless     (solve a xcb compatibility issue)
```

**Comment by worldemar** [comment]
Encountered this issue.
Installing headless opencv worked for me.

> A user in reddit suggested this:
> 
> ```
> pip uninstall opencv-python     (solve a xcb compatibility issue)
> 
> pip install opencv-python-headless     (solve a xcb compatibility issue)
> ```
